

server:
  port: 8888
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MartinCantillo/Microservices-config.git
          search-paths: configs #file or directory

